
const links = [
  {
    name: "Bar",
    url: "#",
  },
  {
    name: "Restaurante",
    url: "#",
  },
  {
    name: "Café",
    url: "#",
  },
];

const data=[
  {
    titles:"Entrantes Fríos y Calientes /",
    titlee:'Cold and Hot Starters',
    name: "Ensalada de frutas tropicales",
    desc: "(Vegetales, jamón y queso / Vegetable, ham and cheese)",
    traduc: "Tropical fruits salad .",
    precio: "70.00",
    point: " ............................................................",
  },
  {
    title:"",
    name: "Ensalada de la casa",
    desc: "",
    traduc: "House salad",
    precio: "280.00",
    point: "...............................................................",
  },
  {
    title:"",
    name: "Rollitos de jamón y queso",
    desc: "",
    traduc: "Ham and cheese rolls ",
    precio: " 470.00",
    point: " ...........................................................",
  },
  {
    title:"",
    name: "Dados de queso",
    desc: "",
    traduc: "Cheese dices",
    precio: "235.00",
    point:
      ".....................................................................",
  },
  {
    title:"",
    name: "Bolitas de queso",
    desc: "",
    traduc: "Cheese of balls ",
    precio: "235.00",
    point: "................................................................. ",
  },

  {
    title:"",
    name: "Croquetas",
    desc: "",
    traduc: "Croquette",
    precio: "20.00",
    point:
      "....................................................................................",
  },
  {
    title:"",
    name: "Consomé mixto",
    desc: "(Caldo de res con vegetales / Beef soup with vegetables)",
    traduc: "Mixed consomé",
    precio: "80.00",
    point:
      ".................................................................. ",
  },
  {
    titles:"Especialidad de la Casa /",
    titlee:' Our specialtys',
    name: "Pierna de cerdo asada al carbón",
    desc: `(Pierna de cerdo asada al carbón macerado con sal, ajo, pimienta, comino, jugo de naranja agria /
  Pork slices with garlic, pepper, cumin and orange juice)`,
    traduc: "Roasted pork",
    precio: "850.00",
    point: "....................................... ",
  },
  {
    titles:"Platos principales /",
    titlee:"Main dishes",
    name: "Masas de cerdo fritas",
    desc: "",
    traduc: "Frieds pork chuncks",
    precio: "850.00",
    point: "................................................................",
  },
  {
    title:"",
    name: "Costilla de cerdo asada",
    desc: "",
    traduc: " Roasted pork rib",
    precio: "450.00",
    point: "................................................................",
  },
  {
    title:"",
    name: "Filete de pescado a la plancha",
    desc: "",
    traduc: "Grilled fish fillet",
    precio: "450.00",
    point: ".............................................................",
  },
  {
    title:"",
    name: "Ruedas de pescado fritas",
    desc: "",
    traduc: "Fried fish wheel",
    precio: "550.00",
    point: "...............................................................",
  },
  {
    title:"",
    name: "Pollo asado al carbón",
    desc: `
    (Pollo asado al carbón macerado con sal, ajo, pimienta, comino, jugo de naranja agria / Chicken with
    garlic, pepper, cumin and orange juice)`,
    traduc: "Roasted chicken style",
    precio: "850.00",
    point: "....................................................",
  },
  {
    title:"",
    name: "Pollo frito a la Criolla",
    desc: "",
    traduc: "Chicken fried, Creole style",
    precio: "550.00",
    point: "..........................................................",
  },
  {
    title:"",
    name: "Suprema de pollo al ajillo",
    desc: "",
    traduc: "Chicken supreme in garlic seasoned",
    precio: "500.00",
    point: ".................................................",
  },
  {
    title:"",
    name: "Ternera guisada",
    desc: "",
    traduc: "Veal in spicy tomato sauce",
    precio: "380.00",
    point: "..............................................................",
  },
  {
    title:"",
    name: "Ropa vieja",
    desc: "",
    traduc: "Minced beef ",
    precio: "380.00",
    point: "............................................................................",
  },
  {
    title:"",
    name: "Chilindrón de cordero",
    desc: "",
    traduc: "Lamb in tomato and pepper sauce",
    precio: "850.00",
    point: ".........................................................",
  },
  {
    titles:"Huevos /",
    titlee:' Eggs',
      name: "Huevos fritos ",
      desc: "",
      traduc: "Fried eggs",
      precio: "40.00",
      point: "............................................................",
    },
    {
      titles:"",
      titlee:'',
      name: "Tortilla natural ",
      desc: "",
      traduc: "Natural omelet .",
      precio: "40.00",
      point: "..................................................................",
    },


    {
      titles:"Guarniciones /",
      titlee:'Accompaniments',
      name: "Moros y Cristianos ",
      desc: "",
      traduc: "Rice and black beans mixed ",
      precio: "50.00",
      point: "........................................",
    },
    {
      titles:"",
      titlee:'',
      name: "Arroz blanco ",
      desc: "",
      traduc: "Boiled rice ",
      precio: "40.00",
      point: "..............................................................................",
    },
    {
      titles:"",
      titlee:'',
      name: "Arroz con vegetales ",
      desc: "",
      traduc: "Rice with vegetables",
      precio: "120.00",
      point: "................................................",
    },
    {
      titles:"",
      titlee:'',  
      name: "Vianda cocida con mojo criollo ",
      desc: "",
      traduc: "Boiled vegetable roots with creole sausage",
      precio: "100.00",
      point: "..............",
    },
    {
      titles:"",
      titlee:'',
      name: "Vianda frita",
      desc: "",
      traduc: "Fried vegetable roots",
      precio: "100.00",
      point: "",
    },    

    {
      titles:"Ensalada de vegetales /",
      titlee:' Vegetable salads',
      name: "Ensalada de vegetales",
      desc: "",
      traduc: "Vegetable salad ",
      precio: "100.00",
      point: ".....................................................",
    }, 
    {
      titles:"",
      titlee:'',
      name: "Vegetales salteados",
      desc: "",
      traduc: "Sauté vegetables .",
      precio: "120.00",
      point: "...................................................... ",
    }, 

    {
      titles:"Postres /",
      titlee:'Desserts',
      name: "Arroz con leche ",
      desc: "",
      traduc: "Rice Pudding ",
      precio: "50.00",
      point: "...................................................................... ",
    }, 
    {
      titles:"",
      titlee:'',
      name: "Buñuelo en almíbar",
      desc: "",
      traduc: "Fritter in syrup ",
      precio: "40.00",
      point: "............................................................",
    }, 
    {
      titles:"",
      titlee:'',
      name: "Dulce de frutas en almíbar ",
      desc: "",
      traduc: "Fruits in syrup",
      precio: "50.00",
      point: "................................................. ",
    }, 

    {
      titles:"Café y té /",
      titlee:'Coffe and tea',
      name: "Café criollo",
      desc: "",
      traduc: "Creole coffee ",
      precio: "25.00",
      point: ".............................................................................. ",
    }, 
    {
      titles:"",
      titlee:'',
      name: "Café Americano ",
      desc: "",
      traduc: "American coffee",
      precio: "25.00",
      point: "..............................................................  ",
    }, 
    {
      titles:"",
      titlee:'',
      name: "Té caliente ",
      desc: "",
      traduc: "Hot tea",
      precio: "25.00",
      point: "......................................................................................",
    }, 
    {
      titles:"",
      titlee:'',
      name: "Té helado",
      desc: "",
      traduc: " Ice tea",
      precio: "25.00",
      point: ".......................................................................................... ",
    }, 

]

export  {links,data}  